"""empty message

Revision ID: 42e5c32079aa
Revises: 
Create Date: 2024-09-05 16:32:53.969440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42e5c32079aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('db_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_db_user_name'), ['name'], unique=True)

    op.drop_table('airport_data')
    with op.batch_alter_table('flight_timing_data', schema=None) as batch_op:
        batch_op.drop_index('航班ID')

    op.drop_table('flight_timing_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_timing_data',
    sa.Column('航班ID', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('航司', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('航班号', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('起始城市', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('起始时间', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('flight_timing_data', schema=None) as batch_op:
        batch_op.create_index('航班ID', ['航班ID'], unique=False)

    op.create_table('airport_data',
    sa.Column('城市名', mysql.TEXT(), nullable=True),
    sa.Column('机场三字码', mysql.TEXT(), nullable=True),
    sa.Column('机场四字码', mysql.TEXT(), nullable=True),
    sa.Column('机场名称', mysql.TEXT(), nullable=True),
    sa.Column('英文名称', mysql.TEXT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('db_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_db_user_name'))

    op.drop_table('db_user')
    # ### end Alembic commands ###
