"""empty message

Revision ID: cd9b1725c35d
Revises: 
Create Date: 2024-09-08 18:46:40.052405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9b1725c35d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airport_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airport_IATA', sa.String(length=3), nullable=True),
    sa.Column('city_name', sa.String(length=100), nullable=True),
    sa.Column('airport_name_cn', sa.String(length=100), nullable=True),
    sa.Column('airport_name_en', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('airport_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_airport_data_airport_IATA'), ['airport_IATA'], unique=True)
        batch_op.create_index(batch_op.f('ix_airport_data_city_name'), ['city_name'], unique=False)

    op.create_table('flight_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_number', sa.String(length=10), nullable=True),
    sa.Column('airline_code', sa.String(length=10), nullable=True),
    sa.Column('airline_num', sa.String(length=10), nullable=True),
    sa.Column('schedule_city', sa.String(length=20), nullable=True),
    sa.Column('schedule_timing', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flight_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flight_schedule_flight_number'), ['flight_number'], unique=True)

    op.create_table('supplier_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_data_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_data_contact_info'), ['contact_info'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_data_contact_person'), ['contact_person'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_data_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_data_create_date'), ['create_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_data_last_updated'), ['last_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_data_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_data_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_data_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_data_status'), ['status'], unique=False)

    op.create_table('system_account_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tour_product_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tour_product_data')
    op.drop_table('system_account_data')
    with op.batch_alter_table('supplier_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_data_status'))
        batch_op.drop_index(batch_op.f('ix_supplier_data_region'))
        batch_op.drop_index(batch_op.f('ix_supplier_data_rating'))
        batch_op.drop_index(batch_op.f('ix_supplier_data_name'))
        batch_op.drop_index(batch_op.f('ix_supplier_data_last_updated'))
        batch_op.drop_index(batch_op.f('ix_supplier_data_create_date'))
        batch_op.drop_index(batch_op.f('ix_supplier_data_country'))
        batch_op.drop_index(batch_op.f('ix_supplier_data_contact_person'))
        batch_op.drop_index(batch_op.f('ix_supplier_data_contact_info'))
        batch_op.drop_index(batch_op.f('ix_supplier_data_address'))

    op.drop_table('supplier_data')
    with op.batch_alter_table('flight_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flight_schedule_flight_number'))

    op.drop_table('flight_schedule')
    with op.batch_alter_table('airport_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_airport_data_city_name'))
        batch_op.drop_index(batch_op.f('ix_airport_data_airport_IATA'))

    op.drop_table('airport_data')
    # ### end Alembic commands ###
